#pragma once

#include <iostream>
#include <iomanip>
#include <string>
#include <filesystem>
#include <windows.h>
#include <sstream>
#include <limits>
#include <thread>
#include <chrono>
#include <stdio.h>
#include <stdlib.h>
#include <conio.h>
#include <ctime>
#include <cstdlib>
#include <vector>
#include <memory>
#include <shlobj.h>
#include <fstream>
#include <cstring>
